package com.eschloff.projectEuler;

//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

public class Problem2 {

	public static void main(String[] args) {
		System.out.print(sumOfEvenFibonacci(4000000));
	}
	
	public static int sumOfEvenFibonacci(int max) {
		int currentSum = 0;
		int fib1 = 1;
		int fib2 = 2;
		while (fib2 < max) {
			if (fib2 / 2 * 2 == fib2) {
				currentSum += fib2;
			}
			fib2 = fib1 + fib2;
			fib1 = fib2 - fib1;
		}
		return currentSum;
	}

}
